const ITData=[
    {
        id:'1',
        title:"JavaScript",
        image:"./Images/javascript.png",
        rating:"4.7(128348)",
        lecture:"18",
        time:"3.2"
    },
    {
        id:'2',
        title:"C++",
        image:"./Images/cpp.jpg",
        rating:"4.1(8236213)",
        lecture:"38",
        time:"4.5"
    },
    {
        id:'3',
        title:"Python",
        image:"./Images/python.jpg",
        rating:"3.9(439123)",
        lecture:"19",
        time:"2.5"
    },
    {
        id:'4',
        title:"Kotlin",
        image:"./Images/kotlin.png",
        rating:"4.4(88811)",
        lecture:"24",
        time:"3.2"
    },
    {
        id:'5',
        title:"JAVA",
        image:"./Images/java.jpg",
        rating:"3.6(762372)",
        lecture:"21",
        time:"3.0"
    },
    {
        id:'6',
        title:"PHP",
        image:"./Images/php.png",
        rating:"3.6(762372)",
        lecture:"43",
        time:"3.9"
    },
    {
        id:'7',
        title:"Swift",
        image:"./Images/swift.png",
        rating:"3.6(762372)",
        lecture:"43",
        time:"3.9"
    },
    {
        id:'8',
        title:"Scala",
        image:"./Images/scala.jpg",
        rating:"3.6(762372)",
        lecture:"43",
        time:"3.9"
    },
]
export default ITData;